[workspace]
members = [
    "playground",
    "benches",
    "arche_tape",
    "untyped_vec",
]

[profile.bench]
opt-level = 3
codegen-units = 1
lto = "thin"
debug = true
panic = "abort"

[profile.release]
opt-level = 3
debug = true 