[workspace]
members = ["playground", "benches", "arche_tape", "untyped_vec",
]

[profile.bench]
codegen-units = 1
debug = true
lto = "thin"
opt-level = 3
panic = "abort"

[profile.release]
debug = true 
opt-level = 3
